function p = defaultParameters()
%DEFAULTPARAMETERS Editable SI inputs. Estimates are NOT measured car data.
% See docs/model.md for provenance, equations, and calibration priorities.
p.vehicle.chassis_mass_kg = sum([61 61 65]/2.205)-1.2; % Legacy scale sum; driver inclusion unknown
p.vehicle.driver_mass_kg = 70;          % Placeholder; set 0 if scale mass includes driver
p.vehicle.wheel_radius_m = 0.2413;      % Loaded rolling radius, not rim radius
p.vehicle.wheel_inertia_kgm2 = 3*(0.5*0.65*0.203^2 + 0.5*0.35*(0.2413^2+0.203^2));
p.vehicle.wheelbase_m = 1.397;
p.vehicle.front_track_m = 0.8;         % Placeholder, two front wheels + one rear
p.vehicle.cg_from_front_m = 1.397*65/187; % Combined car + driver CG; legacy fraction
p.vehicle.cg_height_m = 0.375;
p.vehicle.cg_lateral_offset_m = 0;
p.vehicle.max_brake_force_N = 400;      % Ideal distribution across all wheels
p.aero.cd = 0.10;
p.aero.frontal_area_m2 = 0.71;
p.aero.force_height_m = 0.375;
p.tires.crr = 0.0056;
p.tires.crr_speed_per_mps = 0;         % Optional additive Crr coefficient per m/s
p.tires.friction_coefficient = 0.7;
p.tires.corner_utilization = 0.8;      % Leaves tire/stability margin below static limit
p.drivetrain.gear_ratio = 9.23;
p.drivetrain.efficiency = 0.93;
p.drivetrain.coast_drag_N = 0;         % Freewheel assumption; add measured residual drag
p.motor.torque_constant_Nm_A = 0.136;  % Effective DC kt=ke in SI; calibrate to controller
p.motor.resistance_ohm = 0.275;
p.motor.loss_torque_Nm = 0.0269;
p.motor.viscous_loss_Nm_per_rad_s = 1.55e-5;
p.motor.max_current_A = 10;            % Effective motor current, distinct from pack current
p.motor.max_torque_Nm = 1.2;
p.motor.max_power_W = 500;
p.motor.max_rpm = 4500;
p.controller.efficiency = 0.95;
p.controller.max_duty_cycle = 1;
p.battery.open_circuit_voltage_V = 60;
p.battery.internal_resistance_ohm = 0.15; % Placeholder constant OCV/resistance battery
p.battery.max_current_A = 10;
p.battery.max_terminal_power_W = 600;
p.battery.min_terminal_voltage_V = 45;
p.battery.usable_capacity_Wh = 150;    % Chemical energy budget, placeholder
p.auxiliary.power_W = 5;              % Sensors, controller idle, communications, etc.
p.environment.air_density_kgpm3 = 1.20;
p.environment.headwind_mps = 0;        % Positive opposing local travel, NOT a compass wind
p.environment.gravity_mps2 = 9.81;
p.strategy.mode = 'pulse_coast';       % 'cruise' or 'pulse_coast'
p.strategy.cruise_speed_mps = 17.5*0.44704;
p.strategy.pulse_min_speed_mps = 16.5*0.44704;
p.strategy.pulse_max_speed_mps = 18.5*0.44704;
p.strategy.pulse_motor_torque_Nm = 0.9;
p.strategy.braking_deceleration_mps2 = 0.6; % Approach planning, hard limit is tire/brake force
p.strategy.coast_lookahead_m = 200;    % Coast early for upcoming lower speed limits
p.race.laps = 4;
p.race.time_limit_s = 35*60;           % User-supplied attempt requirement
p.race.minimum_average_speed_mps = 16.6*0.44704; % User planning constraint
p.race.minimum_total_mass_kg = 50;     % User-supplied lower bound, not baseline mass
p.race.target_mi_per_kWh = 300;        % Design goal at battery terminals
p.sim.dt_s = 0.25;
p.sim.max_time_s = 3600;
p.sim.initial_speed_mps = 0;
p.sim.speed_tolerance_mps = 0.05;       % Report physical speed-limit violations beyond this
end
