function row = studyCase(p, track, parameterPath, requestedValue, isFactor)
%STUDYCASE Evaluate one independent candidate and retain rejected inputs.
row = struct( ...
    'parameter_value', NaN, ...
    'valid', false, ...
    'completed', false, ...
    'distance_m', NaN, ...
    'time_s', NaN, ...
    'terminal_energy_Wh', NaN, ...
    'battery_energy_Wh', NaN, ...
    'Wh_per_km', NaN, ...
    'km_per_kWh', NaN, ...
    'mi_per_kWh', NaN, ...
    'within_time_limit', false, ...
    'within_capacity', false, ...
    'physically_feasible', false, ...
    'feasible', false, ...
    'target_met', false, ...
    'energy_budget_Wh', NaN, ...
    'energy_margin_Wh', NaN, ...
    'status', "invalid", ...
    'error_identifier', "", ...
    'error_reason', "");
try
    if nargin >= 3
        parts = strsplit(char(parameterPath), '.');
        currentValue = readParameter(p, parts);
        if isFactor
            requestedValue = currentValue * requestedValue;
        end
        row.parameter_value = requestedValue;
        p = writeParameter(p, parts, requestedValue);
    end
    result = lapsim.simulate(p, track);
    names = {'completed', 'distance_m', 'time_s', ...
        'terminal_energy_Wh', 'battery_energy_Wh', 'Wh_per_km', ...
        'km_per_kWh', 'mi_per_kWh', 'within_time_limit', ...
        'within_capacity', 'physically_feasible', 'feasible', ...
        'target_met', 'energy_budget_Wh', 'energy_margin_Wh'};
    for index = 1:numel(names)
        row.(names{index}) = result.summary.(names{index});
    end
    row.valid = true;
    if row.feasible
        row.status = "feasible";
    else
        row.status = "infeasible";
    end
catch problem
    row.error_identifier = string(problem.identifier);
    row.error_reason = string(problem.message);
end
end

function value = readParameter(p, parts)
value = p;
for index = 1:numel(parts)
    field = parts{index};
    if ~isvarname(field) || ~isstruct(value) || ~isscalar(value) || ...
            ~isfield(value, field)
        error('lapsim:UnknownStudyParameter', ...
            'Parameter path "%s" does not identify an existing field.', ...
            strjoin(parts, '.'));
    end
    value = value.(field);
end
if ~isnumeric(value) || ~isreal(value) || ~isscalar(value)
    error('lapsim:InvalidStudyParameter', ...
        'Parameter "%s" must be a real numeric scalar.', strjoin(parts, '.'));
end
end

function p = writeParameter(p, parts, value)
% MATLAB structs have value semantics, so every candidate starts from p.
if numel(parts) == 1
    p.(parts{1}) = value;
else
    p.(parts{1}) = writeParameter(p.(parts{1}), parts(2:end), value);
end
end
